### ISSUE TITLE
Dialog Error

### ISSUE THREAD

**Issue by kengoon** [quitegreensky/akivymd#17]
the radius property of AKDialog is not declared properly(It is throwing an error), Use ListProperty instead of NumericProperty.

**Comment by quitegreensky** [comment]
@kengoon This problem is already fixed in https://github.com/kivymd-extensions/akivymd

**Comment by kengoon** [comment]
did you move totally to https://github.com/kivymd-extensions/akivymd, my current application depends on this current repo, maybe with time I will shift to https://github.com/kivymd-extensions/akivymd
