### ISSUE TITLE
I have some youtube tutorials i would like to show you

### ISSUE THREAD

**Issue by kengoon** [quitegreensky/akivymd#2]
@quitegreensky Only if you accept, I can give you the link to check it out and add it to the README.md documentation if you like

**Comment by quitegreensky** [comment]
@kengoon Hey thank you for your suggestion but currently making a documentation is the first priority

**Comment by kengoon** [comment]
> @kengoon Hey thank you for your suggestion but currently making a documentation is the first priority 

Ok, notify me whenever you need it
