### ISSUE TITLE
When will have a update for the new kivy and kivymd library?

### ISSUE THREAD

**Issue by RickWalkerOne** [quitegreensky/akivymd#20]
Hello! I loved these plugins, but when I try to use then in my project, a error occur because its works only for the older kivymd versions. So I receive a lot of warnings and errors. If was updated for a new version I will love this!

**Comment by quitegreensky** [comment]
Hey. I haven't been around for a while. I will definitely try to resolve the conflicts. Meanwhile if you have a fix you can make a PR

> Hello! I loved these plugins, but when I try to use then in my project, a error occur because its works only for the older kivymd versions. So I receive a lot of warnings and errors. If was updated for a new version I will love this!

**Comment by quitegreensky** [comment]
> Hello! I loved these plugins, but when I try to use then in my project, a error occur because its works only for the older kivymd versions. So I receive a lot of warnings and errors. If was updated for a new version I will love this!

Use this repo 
https://github.com/kivymd-extensions/akivymd
