### ISSUE TITLE
Problem with datepicker

### ISSUE THREAD

**Issue by Matan22g** [quitegreensky/akivymd#4]
if the user select only 2 options (month/year) it will result in error. 
a fix can be in _choose function:

instead of:

        try:
            date = datetime(
                int(self._year_title),
                int(self._month_title),
                int(self._day_title)
            )
        except:
            self.cancel()
            self.callback(False)

        self.callback(date)
        self.cancel()

something like that:

        try:
            date = datetime(
                int(self._year_title),
                int(self._month_title),
                int(self._day_title)
            )
            self.callback(date)
            self.cancel()
        except:
            self.cancel()
            self.callback(False)

**Comment by quitegreensky** [comment]
Thanks for reporting this bug.

**Comment by kentang2017** [comment]
is it possible to make a datetime picker? i want to add an hour picker widget

**Comment by quitegreensky** [comment]
@kentang2017 there is not such feature yet
