### ISSUE TITLE
Merge with kivymd

### ISSUE THREAD

**Issue by zamirszn** [quitegreensky/akivymd#9]
I couldn't find a better way to contact you
Are you going to merge this with kivy md or make it standalone?

**Comment by zamirszn** [comment]
Is there a proper doc for pyjinius 
Im interested in this project but i cant find a better pyjinius doc

**Comment by quitegreensky** [comment]
> Are you going to merge this with kivy md or make it standalone

KivyMD is following material design rules but akivymd is trying to make those widgets that does not fit into the material shapes. Also akivymd is written based on Kivy and KivyMD so cannot be used like a stand-alone package.

> Im interested in this project but i cant find a better pyjinius doc

We do not use pyjinus
